### ISSUE TITLE
Implement - Message shown for entering non numeric values.

### ISSUE THREAD

**Issue by Neel-07** [Neel-07/Temperature-Converter#12]
Error Handling: Implement robust error handling to deal with invalid inputs. For example, if a user enters a non-numeric value, the application should display a friendly error message.

**Comment by amitesh-183** [comment]
Can You assign it to me??

**Comment by vishal-sharma-369** [comment]
Please assign this issue to me.

**Comment by Neel-07** [comment]
sure @vishal-sharma-369 , do star the repo plz.

**Comment by vishal-sharma-369** [comment]
@vishal-sharma-369 ok sir starred it
