### ISSUE TITLE
Restyle Start Tour Button

### ISSUE THREAD

**Issue by Neel-07** [Neel-07/Temperature-Converter#24]
Do some changes to make the button more visually appealing or to match the overall style of the website.

**Comment by aishwarya-mali** [comment]
@Neel-07 Can I work this issue?

**Comment by Neel-07** [comment]
sure @aishwarya-mali go for it.

**Comment by aishwarya-mali** [comment]
@Neel-07 Should I still work on this?

**Comment by Neel-07** [comment]
yes @aishwarya-mali, you can just see the changes made revert the all clear button to its previous one, change the style of the start button. As of now it doesn't look good, the text and logo are not aligned. you can change the logo if you want to  and surely change the style cause as of now it doesn't match with the overall background.

**Comment by aishwarya-mali** [comment]
@Neel-07 Okay. I'll start work on this.
