### ISSUE TITLE
Adding a Header Section.

### ISSUE THREAD

**Issue by Neel-07** [Neel-07/Temperature-Converter#25]
### Description:
The current application lacks a header section. A well-designed header can improve the user experience by providing easy navigation and access to important information. Adding a header section that includes a home bar.

### Expected Behavior:
The header should be visible at the top of every page. It should include:

1. A home bar that takes users back to the main page.
2. The name or logo of the application.
3. Any other important links or information relevant to the application.

**Comment by devham236** [comment]
hey @Neel-07 i would love to work on this issue also

**Comment by Neel-07** [comment]
Hey @devham236 would you like to work on this issue?

**Comment by Neel-07** [comment]
done @devham236

**Comment by LyubomirT** [comment]
Hello @Neel-07, I'd like to work on this issue. Could you please assign it to me?

**Comment by LyubomirT** [comment]
Oh, I seem to be late, there is already a header bar. Sorry for bothering, I should've been more observant 😅

**Comment by Neel-07** [comment]
no issues @LyubomirT  you can star the repo, will be opening new issues shortly, keep an eye on the repo, and if you have any suggestions on improving or enhancing the site feel free open a new issue.
