### ISSUE TITLE
Adding a demo video to the readme instead of the screenshot.

### ISSUE THREAD

**Issue by Neel-07** [Neel-07/Temperature-Converter#28]
Consider adding a live demo link to the actual converter for users to try it.

**Comment by devham236** [comment]
Hey @Neel-07 i would love to work on this issue.

**Comment by Neel-07** [comment]
sure @devham236 assigning this to you.

**Comment by Neel-07** [comment]
@devham236 merged the pr but the video is not displayed in the readme file, so look into it.

**Comment by devham236** [comment]
@Neel-07, it should display the demo video now, my bad.
