### ISSUE TITLE
Social Media Sharing: 

### ISSUE THREAD

**Issue by Neel-07** [Neel-07/Temperature-Converter#29]
Add Open Graph and Twitter Card tags to your site to enable better sharing on social media platforms.

**Comment by amitesh-183** [comment]
Can you Assign this to me

**Comment by Neel-07** [comment]
sure @amitesh-183 assigning to you.

**Comment by amitesh-183** [comment]
![Screenshot 2023-10-19 235854](https://github.com/Neel-07/Temperature-Converter/assets/80208506/30944530-33b0-4d7d-bf6a-52c9a27a34ac)

OG Is working fine
