### ISSUE TITLE
Add responsiveness to the site

### ISSUE THREAD

**Issue by Neel-07** [Neel-07/Temperature-Converter#36]
The site is currently not responsive, make some code changes so that the site becomes responsive again.

**Comment by AfzalAnsariMd** [comment]
Hey, I would like to work on this. Can you please assign this to me?

**Comment by Neel-07** [comment]
sure @AfzalAnsariMd assigning it to you, can you plz star the repo.

**Comment by harshit1142** [comment]
Please /assign this to me .Really Interested

**Comment by harshit1142** [comment]
@Neel-07  Made PR recently.

**Comment by Neel-07** [comment]
@harshit1142 added a comment to it check once.
