### ISSUE TITLE
Align Header Text and Icon for Better Aesthetics

### ISSUE THREAD

**Issue by Neel-07** [Neel-07/Temperature-Converter#38]
Center and align the header text and temperature icon to enhance the visual appeal of the header section.

**Comment by harshit1142** [comment]
Interested. Please assign this to me .

**Comment by Neel-07** [comment]
@harshit1142 assigned.

**Comment by mudasir5454** [comment]
Off page SEO Unique Domain website comment Service is very essential factor strategy in SEO marketing. Top stage domains are living body of any web site in regards to improving your keywords to the most truly effective of Google SERP. Backlinks  [blog comment](https://www.fiverr.com/mds_service/provide-250-high-da-unique-blog-comment-with-low-spam)  has an Immense Affect websites position browsing engine results. That are the reason they seen as important for improving a website's SEO ranking.. More traffic to your website. Make your website more visible.
