### ISSUE TITLE
The deployed github page doesn't show the Heading temperature coverter and the thermometer logo

### ISSUE THREAD

**Issue by Neel-07** [Neel-07/Temperature-Converter#4]
fix the issue where the temperature converter and symbol of thermometer will shown as a heading of the box

<img width="395" alt="image" src="https://github.com/Neel-07/Temperature-Converter/assets/112561276/9b95864b-a571-4bd7-8824-8db7c37d0188">

**Comment by hasan75** [comment]
I would Love to work with this

**Comment by Neel-07** [comment]
sure @hasan75, go for it. Don't forget to  star ⭐ the repo
