### ISSUE TITLE
Refine Styling of "Start Tour" and "All Clear" Buttons

### ISSUE THREAD

**Issue by Neel-07** [Neel-07/Temperature-Converter#41]
Improve the styling of the "Start Tour" and "All Clear" buttons to enhance their visibility and aesthetics.

**Comment by Dianesaur** [comment]
Heya, can I try to contribute to this project? I don't know much on code as I'm a beginner but I can redesign the buttons if that's what you mean by styling?

**Comment by Neel-07** [comment]
hey @Dianesaur do you know about css ?

**Comment by amitesh-183** [comment]
Hey, I Can Do this Can you assign this to me??

**Comment by Dianesaur** [comment]
@Neel-07 I don’t sadly, but I can find a tutorial on YouTube or ask my APSCP teacher tomorrow to help?

**Comment by Neel-07** [comment]
@amitesh-183 assigned this to you.

**Comment by Neel-07** [comment]
@Dianesaur, dont worry lets the remaining issues get resolved then you can update the README Documentation, you can contribute to it.
