### ISSUE TITLE
Adjust Footer Design for Improved Aesthetics

### ISSUE THREAD

**Issue by Neel-07** [Neel-07/Temperature-Converter#43]
Make adjustments to the footer section's design to enhance its visual appeal and alignment on various screen sizes.

**Comment by abhaysinghr516** [comment]
If available, I would like to work on this

**Comment by Neel-07** [comment]
assigned @abhaysinghr516, plz star the repo.

**Comment by harshit1142** [comment]
Please Sir, Assign this to me.
