### ISSUE TITLE
SEO Optimization

### ISSUE THREAD

**Issue by Neel-07** [Neel-07/Temperature-Converter#51]
Improve the website's SEO by adding meta tags, descriptions, and keywords to enhance its discoverability in search engines.

**Comment by annaw3** [comment]
SEO London is a term that can refer to two things:

SEO services in London: This refers to the services that digital marketing agencies in London offer to help businesses improve their search engine rankings and visibility.
[SEO London](https://webiocreatives.uk/seo-services-london/), the charity: This is a registered charity in the UK that helps young people from disadvantaged backgrounds achieve their educational and career goals.

**Comment by harshit1142** [comment]
/asign me , i wanted to work on it.
