### ISSUE TITLE
Add a background

### ISSUE THREAD

**Issue by Neel-07** [Neel-07/Temperature-Converter#6]
currently the page have a white background, change the color of the background to match the temperature converter box.

**Comment by Vidhanvyrs** [comment]
hey @Neel-07  I would like to contribute to this issue under hacktoberfest label Can you assign this to me

**Comment by vishal-sharma-369** [comment]
Sir please assign this issue to me.

**Comment by Neel-07** [comment]
@Vidhanvyrs are you still working on this.

**Comment by Vidhanvyrs** [comment]
Yes I am it's just I've been stuck with my exams but gonna soon(mostly tommorow) create the PR for the issue 🙂

**Comment by Neel-07** [comment]
@Vidhanvyrs check the files changed by you the changes doesn't reflect on the site(after mereging)
