### ISSUE TITLE
Add favicon to the page.

### ISSUE THREAD

**Issue by Neel-07** [Neel-07/Temperature-Converter#7]
Add a favicon (thermometer) to the page.
You can Something like this - https://www.flaticon.com/free-icon/thermometer_2100100?term=thermometer&page=1&position=3&origin=tag&related_id=2100100

**Comment by adityaphasu** [comment]
Hey! I'd like to work on this issue.

**Comment by Neel-07** [comment]
Sure @adityaphasu go ahead, don't forget to ⭐ the repo #

**Comment by adityaphasu** [comment]
@Neel-07 Done with it!
