### ISSUE TITLE
Upgrade the UI 

### ISSUE THREAD

**Issue by Neel-07** [Neel-07/Temperature-Converter#8]
currently the UI looks kind a simple add some elements and color scheme to make it look more enhanced.

**Comment by aishwarya-mali** [comment]
@Neel-07 Can I work on this issue?

**Comment by Neel-07** [comment]
@aishwarya-mali The page lacks a clear and catchy headline that tells the user what your website is about and why they should use it. You should add a headline that summarizes the value proposition of your temperature converter tool and captures the user’s attention. For example, you could use something like “Convert temperatures in seconds with our easy and accurate tool” or “The ultimate temperature converter for all your needs but the title need to be short.website also lacks a clear call to action that guides the user to perform the desired action, which is converting temperatures. You should add a button or a link that invites the user to use your tool or learn more about it. For example, you could use something like “Start converting now” or “How it works###

**Comment by Neel-07** [comment]
Consider modernizing the UI with a more contemporary design. This could include using a minimalist design, attractive color schemes, and intuitive icons.

**Comment by Aabiskar-dhenga** [comment]
@Neel-07  Look at the PR I HAVE CREATED AND GIVE SOME FEEDBACK . HOPE FOR POSITIVE RESPONSE

**Comment by amitesh-183** [comment]
Can you Assign it to me??

**Comment by vishal-sharma-369** [comment]
Sir please assign this issue to me.
